# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e574ed4b18b0eaadc95051b2f4341ab6"
application_url = "https://reviewsloom.vercel.app"
embedded = true
name = "Review Loom"

[app_proxy]
url = "/api"
subpath = "reviewloom"
prefix = "apps"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_themes"

[auth]
redirect_urls = [ "https://reviewsloom.vercel.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
