# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "81fb4a205e84f0797b409983b3f51061"
application_url = "https://reviewsloom.vercel.app"
embedded = true
name = "Wbify Reviews"

[app_proxy]
url = "/api/reviews"
subpath = "reviewloom"
prefix = "apps"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/fulfilled"
  topics = [ "orders/fulfilled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://reviewsloom.vercel.app/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
