# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "059bbf8a07941adcaf78ae44d65aa041"
name = "Wbify Reviews"
application_url = "https://reviewsloom.vercel.app"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
